=== Metron-Project/metroninfo/drafts/v1.0/MetronInfo.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="MetronInfo" type="metroninfoType" />

    <!-- Complex Types -->
    <xs:complexType name="metroninfoType">
        <xs:all>
            <xs:element name="ID" type="sourceType" minOccurs="0" />
            <xs:element name="Publisher" type="resourceType" />
            <xs:element name="Series" type="seriesType" />
            <xs:element name="CollectionTitle" type="xs:string" minOccurs="0" />
            <xs:element name="Number" type="xs:string" minOccurs="0" />
            <xs:element name="Stories" type="storyType" minOccurs="0" /> <!-- Story titles in issue -->
            <xs:element name="Summary" type="xs:string" minOccurs="0" />
            <xs:element name="Prices" type="pricesType" minOccurs="0" />
            <xs:element name="CoverDate" type="xs:date" />
            <xs:element name="StoreDate" type="xs:date" minOccurs="0" />
            <xs:element name="PageCount" type="xs:int" minOccurs="0" default="0" />
            <xs:element name="Notes" type="xs:string" minOccurs="0" />
            <xs:element name="Genres" type="genresType" minOccurs="0" />
            <xs:element name="Tags" type="tagsType" minOccurs="0" />
            <xs:element name="Arcs" type="arcsType" minOccurs="0" />
            <xs:element name="Characters" type="charactersType" minOccurs="0" />
            <xs:element name="Teams" type="teamsType" minOccurs="0" />
            <xs:element name="Locations" type="locationsType" minOccurs="0" />
            <xs:element name="Reprints" type="reprintsType" minOccurs="0" />
            <xs:element name="GTIN" type="gtinType" minOccurs="0" />
            <xs:element name="BlackAndWhite" type="xs:boolean" minOccurs="0" default="false" />
            <xs:element name="AgeRating" type="ageRatingType" minOccurs="0" default="Unknown" />
            <xs:element name="URL" type="xs:string" minOccurs="0" /> <!-- Should we make this an array? -->
            <xs:element name="Credits" type="creditsType" minOccurs="0" />
            <xs:element name="Pages" type="ArrayOfComicPageInfo" minOccurs="0" />
        </xs:all>
    </xs:complexType>

    <xs:complexType name="sourceType">
        <xs:simpleContent>
            <xs:extension base="xs:positiveInteger">
                <xs:attribute name="source" type="informationSource" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="storyType">
        <xs:sequence>
            <xs:element name="Story" type="resourceType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <!-- Base type to add 'id' attribute to the various resources -->
    <xs:complexType name="resourceType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:positiveInteger" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="seriesType">
        <xs:all>
            <xs:element name="Name" type="xs:string" />
            <xs:element name="SortName" type="xs:string" minOccurs="0" />
            <xs:element name="Volume" type="xs:int" minOccurs="0" />
            <xs:element name="Format" type="formatType" minOccurs="0" />
        </xs:all>
        <xs:attribute name="lang" type="languageCode" default="en" />
        <xs:attribute name="id" type="xs:positiveInteger" />
    </xs:complexType>

    <xs:complexType name="charactersType">
        <xs:sequence>
            <xs:element name="Character" type="resourceType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="teamsType">
        <xs:sequence>
            <xs:element name="Team" type="resourceType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="locationsType">
        <xs:sequence>
            <xs:element name="Location" type="resourceType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tagsType">
        <xs:sequence>
            <xs:element name="Tag" type="resourceType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="reprintsType">
        <xs:sequence>
            <xs:element name="Reprint" type="resourceType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="arcsType">
        <xs:sequence>
            <xs:element name="Arc" type="arcType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="arcType">
        <xs:all>
            <xs:element name="Name" type="xs:string" />
            <xs:element name="Number" type="xs:positiveInteger" minOccurs="0" />
        </xs:all>
        <xs:attribute name="id" type="xs:positiveInteger" />
    </xs:complexType>

    <xs:complexType name="creditsType">
        <xs:sequence>
            <xs:element name="Credit" type="creditType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="roleType">
        <xs:simpleContent>
            <xs:extension base="roleValues">
                <xs:attribute name="id" type="xs:positiveInteger" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rolesType">
        <xs:sequence>
            <xs:element name="Role" type="roleType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="creditType">
        <xs:all>
            <xs:element name="Creator" type="resourceType" />
            <xs:element name="Roles" type="rolesType" minOccurs="0" />
        </xs:all>
    </xs:complexType>

    <xs:complexType name="genreType">
        <xs:simpleContent>
            <xs:extension base="genreValues">
                <xs:attribute name="id" type="xs:positiveInteger" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="genresType">
        <xs:sequence>
            <xs:element name="Genre" type="genreType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="pricesType">
        <xs:sequence>
            <xs:element name="Price" type="priceType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="priceType">
        <xs:simpleContent>
            <xs:extension base="xs:decimal">
                <xs:attribute name="country" type="countryCode" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="gtinType">
        <xs:all>
            <xs:element name="ISBN" minOccurs="0" />
            <xs:element name="UPC" minOccurs="0" />
        </xs:all>
    </xs:complexType>

    <xs:complexType name="ArrayOfComicPageInfo">
        <xs:sequence>
            <xs:element name="Page" type="ComicPageInfo" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ComicPageInfo">
        <xs:attribute name="Image" type="xs:int" use="required" />
        <xs:attribute name="Type" type="ComicPageType" default="Story" />
        <xs:attribute name="DoublePage" type="xs:boolean" default="false" />
        <xs:attribute name="ImageSize" type="xs:long" default="0" />
        <xs:attribute name="Key" type="xs:string" default="" />
        <xs:attribute name="Bookmark" type="xs:string" default="" />
        <xs:attribute name="ImageWidth" type="xs:int" default="-1" />
        <xs:attribute name="ImageHeight" type="xs:int" default="-1" />
    </xs:complexType>

    <!-- Simple Types -->
    <xs:simpleType name="formatType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Annual" />
            <xs:enumeration value="Graphic Novel" />
            <xs:enumeration value="Limited" /> <!-- Used for mini/maxi series -->
            <xs:enumeration value="One-Shot" />
            <xs:enumeration value="Series" /> <!-- Needs better name, but used for Ongoing/Cancelled series -->
            <xs:enumeration value="Trade Paperback" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="informationSource">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Comic Vine" />
            <xs:enumeration value="Grand Comics Database" />
            <xs:enumeration value="Marvel" />
            <xs:enumeration value="Metron" />
            <xs:enumeration value="League of Comic Geeks" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="roleValues">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Writer" />
            <xs:enumeration value="Script" />
            <xs:enumeration value="Story" />
            <xs:enumeration value="Plot" />
            <xs:enumeration value="Interviewer" />
            <xs:enumeration value="Artist" />
            <xs:enumeration value="Penciller" />
            <xs:enumeration value="Breakdowns" />
            <xs:enumeration value="Illustrator" />
            <xs:enumeration value="Layouts" />
            <xs:enumeration value="Inker" />
            <xs:enumeration value="Embellisher" />
            <xs:enumeration value="Finishes" />
            <xs:enumeration value="Ink Assists" />
            <xs:enumeration value="Colorist" />
            <xs:enumeration value="Color Separations" />
            <xs:enumeration value="Color Assists" />
            <xs:enumeration value="Color Flats" />
            <xs:enumeration value="Digital Art Technician" />
            <xs:enumeration value="Gray Tone" />
            <xs:enumeration value="Letterer" />
            <xs:enumeration value="Cover" />
            <xs:enumeration value="Editor" />
            <xs:enumeration value="Consulting Editor" />
            <xs:enumeration value="Assistant Editor" />
            <xs:enumeration value="Associate Editor" />
            <xs:enumeration value="Group Editor" />
            <xs:enumeration value="Senior Editor" />
            <xs:enumeration value="Managing Editor" />
            <xs:enumeration value="Collection Editor" />
            <xs:enumeration value="Production" />
            <xs:enumeration value="Designer" />
            <xs:enumeration value="Logo Design" />
            <xs:enumeration value="Translator" />
            <xs:enumeration value="Supervising Editor" />
            <xs:enumeration value="Executive Editor" />
            <xs:enumeration value="Editor In Chief" />
            <xs:enumeration value="President" />
            <xs:enumeration value="Publisher" />
            <xs:enumeration value="Chief Creative Officer" />
            <xs:enumeration value="Executive Producer" />
            <xs:enumeration value="Other" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="genreValues">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Adult" />
            <xs:enumeration value="Crime" />
            <xs:enumeration value="Espionage" />
            <xs:enumeration value="Fantasy" />
            <xs:enumeration value="Historical" />
            <xs:enumeration value="Horror" />
            <xs:enumeration value="Humor" />
            <xs:enumeration value="Manga" />
            <xs:enumeration value="Parody" />
            <xs:enumeration value="Romance" />
            <xs:enumeration value="Science Fiction" />
            <xs:enumeration value="Sport" />
            <xs:enumeration value="Super-Hero" />
            <xs:enumeration value="War" />
            <xs:enumeration value="Western" />
        </xs:restriction>
    </xs:simpleType>
    <!--
        There's no governing body for age ratings, so let's use something fairly simple to cover most cases.
        It won't be perfect, but adding different values for all the different ways publishers use them seems
        unnecessarily difficult. The age ranges are just suggestions.
    -->
    <xs:simpleType name="ageRatingType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Unknown" />
            <xs:enumeration value="Everyone" /> <!-- Appropriate for readers of all ages. -->
            <xs:enumeration value="Teen" /> <!-- Appropriate for readers age 12 and older. -->
            <xs:enumeration value="Teen Plus" /> <!-- Appropriate for readers age 15 and older. -->
            <xs:enumeration value="Mature" /> <!-- Appropriate for readers age 17 and older. -->
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="countryCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z][A-Z]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="languageCode">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z][a-z]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ComicPageType">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="FrontCover" />
                    <xs:enumeration value="InnerCover" />
                    <xs:enumeration value="Roundup" />
                    <xs:enumeration value="Story" />
                    <xs:enumeration value="Advertisement" />
                    <xs:enumeration value="Editorial" />
                    <xs:enumeration value="Letters" />
                    <xs:enumeration value="Preview" />
                    <xs:enumeration value="BackCover" />
                    <xs:enumeration value="Other" />
                    <xs:enumeration value="Deleted" />
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>
</xs:schema>

=== Metron-Project/metroninfo/drafts/v1.0/Sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<MetronInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MetronInfo.xsd">
    <ID>
        <Primary source="Metron">290431</Primary>
        <Alternative source="Comic Vine">12345</Alternative>
        <Alternative source="Grand Comics Database">543</Alternative>
    </ID>
    <Publisher id="12345">
        <Name>DC Comics</Name>
        <Imprint id="1234">Vertigo</Imprint>
    </Publisher>
    <Series id="65478" lang="en">
        <Name>Justice League</Name>
        <SortName>Justice League</SortName>
        <Volume>2</Volume>
        <Format>Single Issue</Format>
        <AlternativeNames>
            <Name id="1234">Foo</Name>
            <Name lang="de">Hüsker Dü</Name>
        </AlternativeNames>
    </Series>
    <Number>1</Number>
    <Stories>
        <Story id="12">Justice League, Part One</Story>
        <Story>Justice League, Part Two</Story>
    </Stories>
    <Summary>In a universe where super heroes are strange and new, Batman has discovered a dark evil that requires him to unite the World Greatest Heroes!</Summary>
    <Notes>Nothing really to say.</Notes>
    <Prices>
        <Price country="US">3.99</Price>
        <Price country="GB">1.51</Price>
    </Prices>
    <CoverDate>2011-10-01</CoverDate>
    <StoreDate>2011-08-31</StoreDate>
    <PageCount>32</PageCount>
    <Genres>
        <Genre id="98745">Super-Hero</Genre>
        <Genre>Crime</Genre>
    </Genres>
    <Tags>
        <Tag id="78945">Foo</Tag>
        <Tag>Bar</Tag>
    </Tags>
    <Arcs>
        <Arc id="78945">
            <Name>Origin</Name>
            <Number>1</Number>
        </Arc>
        <Arc>
            <Name>The New 52!</Name>
        </Arc>
    </Arcs>
    <Characters>
        <Character id="45678">Aquaman</Character>
        <Character>Batman</Character>
        <Character>Cyborg</Character>
        <Character>Deadman</Character>
        <Character>Barry Allen</Character>
        <Character>Hal Jordan</Character>
        <Character>Hawkman</Character>
        <Character>Mera</Character>
        <Character>Pandora</Character>
        <Character>Ray Palmer</Character>
        <Character>Superman</Character>
        <Character>Wonder Woman</Character>
    </Characters>
    <Teams>
        <Team id="49948">Justice League</Team>
        <Team>Parademons</Team>
    </Teams>
    <Universes>
        <Universe id="24">
            <Name>ABC</Name>
            <Designation>Earth 25</Designation>
        </Universe>
        <Universe>
            <Name>Amalgam</Name>
        </Universe>
    </Universes>
    <Locations>
        <Location id="12389">Gotham City</Location>
        <Location>Metropolis</Location>
    </Locations>
    <GTIN>
        <ISBN>1234567890123</ISBN>
        <UPC>76194130593600111</UPC>
    </GTIN>
    <AgeRating>Everyone</AgeRating>
    <Reprints>
        <Reprint id="65498">Foo Bar #001 (2002)</Reprint>
        <Reprint>Foo Bar #002 (2022)</Reprint>
    </Reprints>
    <URL>
        <Primary>https://comicvine.gamespot.com/justice-league-1-justice-league-part-one/4000-290431/</Primary>
        <Alternative>https://foo.bar</Alternative>
    </URL>
    <Credits>
        <Credit>
            <Creator id="32165">Geoff Johns</Creator>
            <Roles>
                <Role id="32165">Writer</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>David Finch</Creator>
            <Roles>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Richard Friend</Creator>
            <Roles>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Jim Lee</Creator>
            <Roles>
                <Role>Penciller</Role>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Scott Williams</Creator>
            <Roles>
                <Role>Inker</Role>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Alex Sinclair</Creator>
            <Roles>
                <Role>Colorist</Role>
                <Role>Cover</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Pat Brosseau</Creator>
            <Roles>
                <Role>Letterer</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Rex Ogle</Creator>
            <Roles>
                <Role>Associate Editor</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Eddie Berganza</Creator>
            <Roles>
                <Role>Editor</Role>
            </Roles>
        </Credit>
        <Credit>
            <Creator>Dan DiDio</Creator>
            <Roles>
                <Role>Publisher</Role>
            </Roles>
        </Credit>
    </Credits>
    <LastModified>2023-05-31T09:00:46.300882-04:00</LastModified>
    <Pages>
        <Page index="0" type="FrontCover" size="1733120" height="2951" width="1920" />
        <Page index="1" size="1320938" height="2951" width="1920" double_page="true" />
        <Page index="2" size="1298224" height="2951" width="1920" />
        <Page index="3" size="1587983" height="2951" width="1920" />
        <Page index="4" size="1840640" height="2951" width="1920" />
        <Page index="5" size="1759923" height="2951" width="1920" />
        <Page index="6" size="1719108" height="2951" width="1920" />
        <Page index="7" size="1776021" height="2953" width="1920" />
        <Page index="8" size="1216900" height="2951" width="1920" />
        <Page index="9" size="1650500" height="2951" width="1920" />
        <Page index="10" size="2544723" height="2998" width="3900" />
        <Page index="11" size="2045030" height="2998" width="3900" />
        <Page index="12" size="1773291" height="2951" width="1920" />
        <Page index="13" size="1780221" height="2951" width="1920" />
        <Page index="14" size="1729622" height="2951" width="1920" />
        <Page index="15" size="1702175" height="2951" width="1920" />
        <Page index="16" size="1574702" height="2951" width="1920" />
        <Page index="17" size="1669914" height="2951" width="1920" />
        <Page index="18" size="1730573" height="2951" width="1920" />
        <Page index="19" size="1765073" height="2951" width="1920" />
        <Page index="20" size="2121982" height="2951" width="1920" />
        <Page index="21" size="1910822" height="2951" width="1920" />
        <Page index="22" size="1611487" height="2951" width="1920" />
        <Page index="23" size="1614281" height="2951" width="1920" />
        <Page index="24" size="2091726" height="2951" width="1920" />
        <Page index="25" size="1908541" height="2951" width="1920" />
        <Page index="26" size="1924791" height="2951" width="1920" />
        <Page index="27" size="1919434" height="2951" width="1920" />
        <Page index="28" size="1658495" height="2951" width="1920" />
        <Page index="29" size="1841634" height="2951" width="1920" />
        <Page index="30" size="1794905" height="2951" width="1920" />
        <Page index="31" size="1950178" height="2951" width="1920" />
        <Page index="32" size="1847993" height="2951" width="1920" />
        <Page index="33" size="3447741" height="2998" width="3900" />
        <Page index="34" size="1758921" height="2951" width="1920" />
        <Page index="35" size="1886432" height="2955" width="1920" />
    </Pages>
</MetronInfo>
